Platform:
    WebPath: http://platform.app:8000
    ApiPath: http://platform.app:8000/api
    AbsPath: __DIR__/../
    UploadsAbsPath: __DIR__/../Public/Uploads
    UploadsWebPath: http://platform.app/Uploads
    AppsPath: __DIR__/../Apps
    AppsWebPath: http://platform.app:8000/Apps
    Backend:
        Prefix: admin
    Error:
        Reporting: true
    Bootstrap:
        App: Core
        Module: Layout
        Component: Layout

Database:
    Host: 127.0.0.1:27017
    Name: webiny-platform

Mongo:
    Services:
        Webiny:
            Class: \Webiny\Component\Mongo\Mongo
            Arguments:
                Host: 127.0.0.1:27017
                Database: webiny-platform
    ResultClass: \Webiny\Component\Mongo\MongoResult

Entity:
    Database: Webiny

Rest:
    Api:
        CompilePath: __DIR__/../Cache/Rest
        Environment: development
        Router:
            Class: \Apps\{app}\{area}\{module}\Php\Services\{service}
            Path: /api/{app}/{area}/{module}/{service}
            Normalize: true

Services:
    Smarty:
        Factory: \Webiny\Platform\Tools\TemplateEngine
        Method: getInstance

TemplateEngine:
    Engines:
        Smarty:
            ForceCompile: true
            CacheDir: __DIR__/../Cache/Smarty/Cache
            CompileDir: __DIR__/../Cache/Smarty/Compile
            TemplateDir: __DIR__/../Public
            AutoEscapeOutput: false
            MergeCompiledIncludes: false

Storage:
    Services:
        Root:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\Local
                    ObjectArguments:
                        - __DIR__/../
        Apps:
            Class: \Webiny\Component\Storage\Storage
            Arguments:
                Driver:
                    Object: \Webiny\Component\Storage\Driver\Local\Local
                    ObjectArguments:
                        - __DIR__/../Apps