version: '2'

services:
    nginx:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - ./:/app
            - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf

    php:
        image: webiny/php7:dev
        volumes:
            - ./:/app:delegated
        environment:
            XDEBUG_CONFIG: "remote_enable=0 remote_host=0.0.0.0"
        extra_hosts: []

    mongodb:
        image: mongo
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 8001:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet